export interface ProformaFullDetailsResponseModel{
        proformaId: number;
        clientRegion: string;
        clientMarket: string;
        clientName: string;
        availableGeneralCommissions: number;
        availableVBISCommissions: number;
        proformaNo: string;
        proformaNotes: string;
        internalNotes: string;
        additionalNotes: string;
        proformaLayoutId: number;
        collectionsContactId: number;
        proformaStatus: string;
        projectRegion: string;
        projectMarket: string;
        projectName: string;
        availableAdvanceBills: number;
        serviceName: string;
        taskName: string;
        hourlyRate: number;
        time: number;
        chargeType: string;
        currency: string;
        description: string;
        proformaTotal: number;
        value: string;
        userName: string 
}